### ISSUE TITLE
eunomia.kohls.com/v1alpha2

### ISSUE THREAD

**Issue by seanmalloy** [KohlsTechnology/eunomia#183]
**Proposal**

This is the initial proposal for changes that will be made to the `eunomia.kohls.io/v1alpha2` CRD. The `v1alpha2` version will tentatively be released in early 2020.

- [ ] Add support for annotations - #153 
- [ ] Move Resource Handling/Deletion mode - #139 
- [ ] Allow overriding Job/CronJob fields in GitOpsConfigs - #366 

Draft CR:
```
Spec:
  serviceAccountRef:
  resourceHandlingMode:
  resourceDeletionMode:
  triggers:
  - type: Change
  - type: Periodic
  - type: Webhook
  templateSource:
    uri:
    ref:
    contextDir:
    secretName:
    httpProxy:
    httpsProxy:
    noProxy:
  parameterSource:
    uri:
    ref:
    contextDir:
    secretName:
    httpProxy:
    httpsProxy:
    noProxy:
  processors:
    args: <<-- have args here instead of sub-levels?
    vcs:
      Image: git vs ??
      Args:
      Cpu:
      Memory:
    parameters:
      Image: hierarchy vs ansible vs ??
      Args:
      Cpu:
      Memory:
    templates: <-- optional / skip for straight up yaml ?
      Image: none vs jinja vs helm vs ansible vs ??
      Args:
      Cpu:
      Memory:
    process:
      Image: kubectl vs oc vs applier vs ???
      Args:
      Cpu:
      Memory:
status:
  completionTime:
  lastScheduleTime:
  message:
  startTime:
  state:
```

**Comment by seanmalloy** [comment]
We had the initial discussion with @akavel, @vinny-sabatini, @mkyc, and @sanbornick. The list of proposed changes is not complete or finalized yet. We are looking for feedback from other people to get a better understanding of what changes people would like to see.

Please add comments here with any ideas.

**Comment by seanmalloy** [comment]
Finishing off adding the remaining fields to the `.status` section mentioned in #101 is a good candidate for `eunomia.kohls.com/v1alpha2`.

**Comment by seanmalloy** [comment]
Also consider #221

**Comment by seanmalloy** [comment]
Also consider #232

**Comment by seanmalloy** [comment]
Based on discussion [here](https://github.com/KohlsTechnology/eunomia/issues/213#issuecomment-570785875) we might want to consider adding an option to allow setting `--wait=false` on all `kubectl delete` commands.

**Comment by Smiley73** [comment]
Also consider #244

**Comment by Algruun** [comment]
Consider to use helm not only as a template engine, but also like some manager via `helm install`/`helm upgrade`. I think this could make control over installed charts easier as you could see installed charts separately of other pods and etc

**Comment by seanmalloy** [comment]
@Algruun thanks for the feedback. If the `helm install / helm upgrade` feature does get added we would only support helm v3, not helm v2.

**Comment by Algruun** [comment]
@seanmalloy isn't possible to determine helm version and use corresponding install method?

**Comment by akavel** [comment]
Please consider #312 for v1alpha2 (in short, I suggest removing "Retain" and/or "None" resourceDeletionMode, with clear documentation for the remaining one, and with a consideration for clearer name)

**Comment by akavel** [comment]
As to the draft CR, additional suggestions:

1. in `processors`, rename `vcs` to `fetch` (I see the meaning as "what app to load params & templates with", not necessarily tied to a VCS at all, could as well be plain curl/wget)
2. in `processors`, add a `discovery`/`discoverEnv` step between vcs and parameters (akin to current discoverEnvironment.sh, with potential to be expanded to gathering info from running cluster in the future)
